spring.application.name=spring-breeze-erp-v2
################################
###    Business Layer        ###
################################
spring.main.web-application-type=servlet
spring.main.banner-mode=off
server.port=8282
#server.servlet.context-path=/spring-breeze-erp-v2

################################
###    DataSource         ###
################################
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=sberp
spring.datasource.password=sberp1234

################################
###    Mybatis              ###
################################
mybatis.type-aliases-package=com.sb.erp
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

################################
###    Thymeleaf           ###
################################
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

###################################
###         Logging             ###
###################################
logging.level.org.hibernate=info
logging.level.org.springframework=info
logging.level.com.the703=debug

###################################
###         Upload             ###
###################################
#  resource.path=src/main/resources/statis/upload/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB  
upload.path=/upload/**
resource.path=C:/upload