spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: sberp
    password: sberp1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update  # test 환경 create-drop 매번 초기화 / update 부분 수정  
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB      

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 2000

#  config:
#    import: 
#      - optional:application-oauth.yml
#      - optional:file:.env[.properties]


#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: com.sb.erp.domain 

#jwt:
#  issuer: thejoa703
#  secret: ${JWT_SECRET}
#  access-token-exp-seconds: 900       
#  refresh-token-exp-seconds: 1209600   
#  header: Authorization
#  prefix: Bearer

#file:
#  upload-dir: uploads
upload:
  path: /upload         # 웹에서 접근할 URL prefix (fileUrl = /upload/**/**/파일명)
resource:
  path: C:/upload       # 실제 디스크 저장 경로 (운영 서버에서는 리눅스 절대경로로 교체)


#server:
#  port: 8484s