-- ============================================================
-- 급여관리(sal) 모듈 + 급여 산정 엔진(calc engine) 더미 데이터 (com_id = 1 기준)
-- salary_calculation_engine_ddl.sql (신규 4개 테이블)이 반영된 것을 전제로 한다.
--
-- 이 스크립트는 [기존 더미 데이터 전체 삭제] -> [정책 테이블부터 새로 등록] -> 
-- [정책 테이블 값(요율/직책수당/소득세 구간/식대)을 실제로 참조해서 산정한 sal_pay/sal_pay_item 재등록]
-- 순서로 동작한다. 즉 06_sal_dummy_data.sql 을 대체한다(그 스크립트는 더 이상 사용하지 않는다).
--
-- salary-calculation-engine-design.md / -implementation.md 의 계산 규칙을 그대로 반영:
--   MEAL_ALLOWANCE            = sal_meal_alw_plcy.amt (com_id=1 우선, 없으면 com_id=NULL 공통값)
--   POSITION_ALLOWANCE        = sal_pos_alw 에서 com_id+pos(POS_CODE) 매칭 (없으면 0)
--   ANNUAL_LEAVE_ALLOWANCE    = 0 (연차 모듈 미연동 스텁 - 항상 0원)
--   OVERTIME_ALLOWANCE        = 0 (근태 모듈 미연동 스텁 - 항상 0원)
--   NATIONAL_PENSION          = baseSal x sal_rate_plcy.pens_rate (원단위 절사)
--   HEALTH_INSURANCE          = baseSal x sal_rate_plcy.hlth_rate (원단위 절사)
--   LONG_TERM_CARE_INSURANCE  = 절사된 HEALTH_INSURANCE x sal_rate_plcy.care_rate (원단위 절사)
--   EMPLOYMENT_INSURANCE      = baseSal x sal_rate_plcy.empl_rate (원단위 절사)
--   INCOME_TAX                = baseSal 이 속한 sal_inc_tax_brkt 구간의 tax_rate x baseSal (원단위 절사)
--   LOCAL_INCOME_TAX          = INCOME_TAX x 10% (원단위 절사)
--
-- SalaryCalculationService 는 SalaryItemCode.values() 10개 항목을 전부 순회하며 후보를 만들어내므로,
-- sal_pay 1건당 sal_pay_item 은 항상 정확히 10건(0원인 항목 포함)이 생성된다.
-- ============================================================

SET DEFINE OFF;

-- ------------------------------------------------------------
-- 1) 기존 더미 데이터 전체 삭제 (FK 자식 -> 부모 순서)
--    sal_pay_item 은 sal_pay 삭제 시 ON DELETE CASCADE 로 이미 함께 삭제되지만,
--    스크립트 재실행 안전성을 위해 명시적으로도 지운다.
-- ------------------------------------------------------------
DELETE FROM sal_hist;
DELETE FROM sal_pay_item;
DELETE FROM sal_pay;
DELETE FROM sal_acct;
DELETE FROM sal_std;
DELETE FROM sal_meal_alw_plcy;
DELETE FROM sal_pos_alw;
DELETE FROM sal_inc_tax_brkt;
DELETE FROM sal_rate_plcy;

-- ------------------------------------------------------------
-- 2) 시퀀스 초기화 (DROP -> CREATE, 테이블 구조는 건드리지 않고 시퀀스만 1부터 재시작)
-- ------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_std_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_std_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_acct_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_acct_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_pay_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_pay_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_pay_item_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_pay_item_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_hist_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_hist_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_rate_plcy_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_rate_plcy_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_pos_alw_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_pos_alw_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_inc_tax_brkt_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_inc_tax_brkt_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sal_meal_alw_plcy_seq'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
CREATE SEQUENCE sal_meal_alw_plcy_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ------------------------------------------------------------
-- 3) sal_rate_plcy : 4대보험 요율 정책 (comId 없음, 전국 공통) - 2건
--    2026년 현재 유효한 1건만 실제 계산에 쓰인다. 2025년은 종료된 이력 예시.
-- ------------------------------------------------------------
Insert into SBERP.SAL_RATE_PLCY (RATE_ID,PLCY_YEAR,PENS_RATE,HLTH_RATE,CARE_RATE,EMPL_RATE,EFF_FROM,EFF_TO) values (1,2025,0.045,0.03495,0.1281,0.008,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD')); -- 종료
Insert into SBERP.SAL_RATE_PLCY (RATE_ID,PLCY_YEAR,PENS_RATE,HLTH_RATE,CARE_RATE,EMPL_RATE,EFF_FROM,EFF_TO) values (2,2026,0.045,0.03545,0.1295,0.009,to_date('26/01/01','RR/MM/DD'),NULL); -- 현재 유효

-- ------------------------------------------------------------
-- 4) sal_pos_alw : 직책별 수당 (com_id=1) - 5건
--    사원(P1)/주임(P2)/대리(P3)는 직책수당 정책이 없음(= 0원, 정책 미존재).
-- ------------------------------------------------------------
Insert into SBERP.SAL_POS_ALW (ALW_ID,POS,COM_ID,AMT,EFF_FROM,EFF_TO) values (1,'P4',1,200000,to_date('26/01/01','RR/MM/DD'),NULL); -- 과장
Insert into SBERP.SAL_POS_ALW (ALW_ID,POS,COM_ID,AMT,EFF_FROM,EFF_TO) values (2,'P5',1,300000,to_date('26/01/01','RR/MM/DD'),NULL); -- 차장
Insert into SBERP.SAL_POS_ALW (ALW_ID,POS,COM_ID,AMT,EFF_FROM,EFF_TO) values (3,'P6',1,400000,to_date('26/01/01','RR/MM/DD'),NULL); -- 부장
Insert into SBERP.SAL_POS_ALW (ALW_ID,POS,COM_ID,AMT,EFF_FROM,EFF_TO) values (4,'P7',1,500000,to_date('26/01/01','RR/MM/DD'),NULL); -- 이사
Insert into SBERP.SAL_POS_ALW (ALW_ID,POS,COM_ID,AMT,EFF_FROM,EFF_TO) values (5,'P4',1,150000,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD')); -- 과장(종료)

-- ------------------------------------------------------------
-- 5) sal_inc_tax_brkt : 소득세 근사 구간표 (comId 없음, 전국 공통) - 10건
--    2026년 5개 구간이 현재 유효. 2025년 5개 구간은 종료된 이력 예시.
--    (부양가족 수 미반영, 포트폴리오/데모용 단순 정률 근사치)
-- ------------------------------------------------------------
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (1,0,3000000,0.028,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD'));
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (2,3000001,4000000,0.033,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD'));
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (3,4000001,5000000,0.038,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD'));
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (4,5000001,6000000,0.043,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD'));
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (5,6000001,NULL,0.048,to_date('25/01/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD'));
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (6,0,3000000,0.03,to_date('26/01/01','RR/MM/DD'),NULL);
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (7,3000001,4000000,0.035,to_date('26/01/01','RR/MM/DD'),NULL);
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (8,4000001,5000000,0.04,to_date('26/01/01','RR/MM/DD'),NULL);
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (9,5000001,6000000,0.045,to_date('26/01/01','RR/MM/DD'),NULL);
Insert into SBERP.SAL_INC_TAX_BRKT (BRKT_ID,MIN_AMT,MAX_AMT,TAX_RATE,EFF_FROM,EFF_TO) values (10,6000001,NULL,0.05,to_date('26/01/01','RR/MM/DD'),NULL);

-- ------------------------------------------------------------
-- 6) sal_meal_alw_plcy : 식대 정책 - 3건
--    com_id=1 전용 정책이 있으므로 실제 계산에는 2번 행(20만원)이 쓰이고,
--    1번 행(comId NULL, 15만원)은 comId 지정 정책이 없는 다른 회사를 위한 전사 공통 fallback 예시.
-- ------------------------------------------------------------
Insert into SBERP.SAL_MEAL_ALW_PLCY (MEAL_PLCY_ID,COM_ID,AMT,EFF_FROM,EFF_TO) values (1,NULL,150000,to_date('25/01/01','RR/MM/DD'),NULL); -- 전사 공통 fallback
Insert into SBERP.SAL_MEAL_ALW_PLCY (MEAL_PLCY_ID,COM_ID,AMT,EFF_FROM,EFF_TO) values (2,1,180000,to_date('25/03/01','RR/MM/DD'),to_date('25/12/31','RR/MM/DD')); -- com_id=1 종료 이력
Insert into SBERP.SAL_MEAL_ALW_PLCY (MEAL_PLCY_ID,COM_ID,AMT,EFF_FROM,EFF_TO) values (3,1,200000,to_date('26/01/01','RR/MM/DD'),NULL); -- com_id=1 현재 유효

-- ------------------------------------------------------------
-- 7) sal_std (급여기준) : 12명 x 1건 + 승진 2명 x 버저닝 2건 = 14건
-- ------------------------------------------------------------
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (1,134,2800000,33600000,to_date('26/05/16','RR/MM/DD'),NULL,1); -- 노경형(사원)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (2,141,3200000,38400000,to_date('26/03/29','RR/MM/DD'),NULL,1); -- 엄정현(주임)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (3,143,3200000,38400000,to_date('26/04/22','RR/MM/DD'),NULL,1); -- 공창형(주임)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (4,132,3700000,44400000,to_date('26/05/04','RR/MM/DD'),NULL,1); -- 허철아(대리)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (5,135,3700000,44400000,to_date('26/01/08','RR/MM/DD'),NULL,1); -- 이규우(대리)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (6,137,3700000,44400000,to_date('26/06/17','RR/MM/DD'),NULL,1); -- 원나희(대리)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (7,138,3700000,44400000,to_date('26/01/20','RR/MM/DD'),NULL,1); -- 주현율(대리)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (8,139,3700000,44400000,to_date('26/05/15','RR/MM/DD'),NULL,1); -- 한도훈(대리)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (9,140,4300000,51600000,to_date('26/06/01','RR/MM/DD'),NULL,1); -- 홍지원(과장)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (10,142,5800000,69600000,to_date('26/07/04','RR/MM/DD'),NULL,1); -- 안예준(부장)
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (11,133,3700000,44400000,to_date('26/06/10','RR/MM/DD'),to_date('26/07/31','RR/MM/DD'),0); -- 류상경(대리) [구 - 승진 전]
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (12,133,4300000,51600000,to_date('26/08/01','RR/MM/DD'),NULL,1); -- 류상경(과장) [신 - 승진 후]
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (13,136,4300000,51600000,to_date('26/04/20','RR/MM/DD'),to_date('26/07/31','RR/MM/DD'),0); -- 노철연(과장) [구 - 승진 전]
Insert into SBERP.SAL_STD (STD_ID,EMP_ID,BASE_SAL,ANNU_SAL,START_DATE,END_DATE,ACTV) values (14,136,5000000,60000000,to_date('26/08/01','RR/MM/DD'),NULL,1); -- 노철연(차장) [신 - 승진 후]

-- ------------------------------------------------------------
-- 8) sal_acct (급여 수령 계좌) : 12명 x 1건
-- ------------------------------------------------------------
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (1,132,'국민은행','123456-78-901234','허철아'); -- 허철아
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (2,133,'신한은행','110-456-789012','류상경'); -- 류상경
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (3,134,'우리은행','1002-345-678901','노경형'); -- 노경형
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (4,135,'하나은행','456-789012-34567','이규우'); -- 이규우
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (5,136,'농협은행','302-1234-5678-91','노철연'); -- 노철연
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (6,137,'카카오뱅크','3333-01-2345678','원나희'); -- 원나희
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (7,138,'IBK기업은행','234567-89-012345','주현율'); -- 주현율
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (8,139,'SC제일은행','110-567-890123','한도훈'); -- 한도훈
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (9,140,'국민은행','1002-456-789012','홍지원'); -- 홍지원
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (10,141,'신한은행','456-012345-01-012','엄정현'); -- 엄정현
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (11,142,'하나은행','567-890123-45678','안예준'); -- 안예준
Insert into SBERP.SAL_ACCT (ACCT_ID,EMP_ID,BANK_NAME,ACCT_NO,HLDR_NAME) values (12,143,'우리은행','123-45-678901','공창형'); -- 공창형

-- ------------------------------------------------------------
-- 9) sal_pay (급여 지급) : 6월 6건 + 7월 12건 = 18건
--    sal_rate_policy(2026,유효)/sal_position_allowance(com_id=1)/
--    sal_income_tax_bracket(2026,유효)/sal_meal_allowance_policy(com_id=1,20만원)를
--    그대로 적용해서 계산한 값이다.
-- ------------------------------------------------------------
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (1,135,5,to_date('26/06/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/07/05','RR/MM/DD'),'하나은행','456-789012-34567','이규우'); -- 이규우 26-06월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (2,138,7,to_date('26/06/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/07/05','RR/MM/DD'),'IBK기업은행','234567-89-012345','주현율'); -- 주현율 26-06월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (3,141,2,to_date('26/06/01','RR/MM/DD'),3200000,200000,424129,2975871,'PAID',NULL,to_date('26/07/05','RR/MM/DD'),'신한은행','456-012345-01-012','엄정현'); -- 엄정현 26-06월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (4,136,13,to_date('26/06/01','RR/MM/DD'),4300000,400000,593575,4106425,'PAID',NULL,to_date('26/07/05','RR/MM/DD'),'농협은행','302-1234-5678-91','노철연'); -- 노철연 26-06월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (5,143,3,to_date('26/06/01','RR/MM/DD'),3200000,200000,424129,2975871,'PAID',NULL,to_date('26/07/05','RR/MM/DD'),'우리은행','123-45-678901','공창형'); -- 공창형 26-06월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (6,132,4,to_date('26/06/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/07/05','RR/MM/DD'),'국민은행','123456-78-901234','허철아'); -- 허철아 26-06월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (7,132,4,to_date('26/07/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'국민은행','123456-78-901234','허철아'); -- 허철아 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (8,133,11,to_date('26/07/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'신한은행','110-456-789012','류상경'); -- 류상경 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (9,134,1,to_date('26/07/01','RR/MM/DD'),2800000,200000,355713,2644287,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'우리은행','1002-345-678901','노경형'); -- 노경형 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (10,135,5,to_date('26/07/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'하나은행','456-789012-34567','이규우'); -- 이규우 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (11,136,13,to_date('26/07/01','RR/MM/DD'),4300000,400000,593575,4106425,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'농협은행','302-1234-5678-91','노철연'); -- 노철연 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (12,137,6,to_date('26/07/01','RR/MM/DD'),3700000,200000,490400,3409600,'REJECTED','급여 수령 계좌 정보 확인 필요로 반려',NULL,'카카오뱅크','3333-01-2345678','원나희'); -- 원나희 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (13,138,7,to_date('26/07/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'IBK기업은행','234567-89-012345','주현율'); -- 주현율 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (14,139,8,to_date('26/07/01','RR/MM/DD'),3700000,200000,490400,3409600,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'SC제일은행','110-567-890123','한도훈'); -- 한도훈 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (15,140,9,to_date('26/07/01','RR/MM/DD'),4300000,400000,593575,4106425,'APPROVED',NULL,NULL,'국민은행','1002-456-789012','홍지원'); -- 홍지원 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (16,141,2,to_date('26/07/01','RR/MM/DD'),3200000,200000,424129,2975871,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'신한은행','456-012345-01-012','엄정현'); -- 엄정현 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (17,142,10,to_date('26/07/01','RR/MM/DD'),5800000,600000,832535,5567465,'PAID',NULL,to_date('26/08/05','RR/MM/DD'),'하나은행','567-890123-45678','안예준'); -- 안예준 26-07월
Insert into SBERP.SAL_PAY (PAY_ID,EMP_ID,STD_ID,PAY_MONTH,BASE_SAL,ALLOW_TOTAL,DEDT_TOTAL,NET_PAY,STAT,REJ_RSN,PAID_AT,BANK_NAME,ACCT_NO,HLDR_NAME) values (18,143,3,to_date('26/07/01','RR/MM/DD'),3200000,200000,424129,2975871,'PENDING',NULL,NULL,'우리은행','123-45-678901','공창형'); -- 공창형 26-07월

-- ------------------------------------------------------------
-- 10) sal_pay_item (급여 지급 세부 항목) : 180건 (18건 x 10개 항목, 0원 스텁 항목 포함)
-- ------------------------------------------------------------
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (1,1,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (2,1,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (3,1,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (4,1,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (5,1,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (6,1,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (7,1,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (8,1,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (9,1,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (10,1,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (11,2,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (12,2,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (13,2,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (14,2,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (15,2,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (16,2,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (17,2,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (18,2,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (19,2,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (20,2,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (21,3,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (22,3,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (23,3,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (24,3,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (25,3,'NATIONAL_PENSION',144000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (26,3,'HEALTH_INSURANCE',113440);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (27,3,'LONG_TERM_CARE_INSURANCE',14690);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (28,3,'EMPLOYMENT_INSURANCE',28799);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (29,3,'INCOME_TAX',112000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (30,3,'LOCAL_INCOME_TAX',11200);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (31,4,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (32,4,'POSITION_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (33,4,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (34,4,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (35,4,'NATIONAL_PENSION',193500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (36,4,'HEALTH_INSURANCE',152435);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (37,4,'LONG_TERM_CARE_INSURANCE',19740);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (38,4,'EMPLOYMENT_INSURANCE',38700);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (39,4,'INCOME_TAX',172000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (40,4,'LOCAL_INCOME_TAX',17200);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (41,5,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (42,5,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (43,5,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (44,5,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (45,5,'NATIONAL_PENSION',144000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (46,5,'HEALTH_INSURANCE',113440);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (47,5,'LONG_TERM_CARE_INSURANCE',14690);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (48,5,'EMPLOYMENT_INSURANCE',28799);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (49,5,'INCOME_TAX',112000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (50,5,'LOCAL_INCOME_TAX',11200);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (51,6,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (52,6,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (53,6,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (54,6,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (55,6,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (56,6,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (57,6,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (58,6,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (59,6,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (60,6,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (61,7,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (62,7,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (63,7,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (64,7,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (65,7,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (66,7,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (67,7,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (68,7,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (69,7,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (70,7,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (71,8,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (72,8,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (73,8,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (74,8,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (75,8,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (76,8,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (77,8,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (78,8,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (79,8,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (80,8,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (81,9,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (82,9,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (83,9,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (84,9,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (85,9,'NATIONAL_PENSION',126000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (86,9,'HEALTH_INSURANCE',99260);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (87,9,'LONG_TERM_CARE_INSURANCE',12854);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (88,9,'EMPLOYMENT_INSURANCE',25199);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (89,9,'INCOME_TAX',84000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (90,9,'LOCAL_INCOME_TAX',8400);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (91,10,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (92,10,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (93,10,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (94,10,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (95,10,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (96,10,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (97,10,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (98,10,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (99,10,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (100,10,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (101,11,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (102,11,'POSITION_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (103,11,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (104,11,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (105,11,'NATIONAL_PENSION',193500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (106,11,'HEALTH_INSURANCE',152435);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (107,11,'LONG_TERM_CARE_INSURANCE',19740);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (108,11,'EMPLOYMENT_INSURANCE',38700);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (109,11,'INCOME_TAX',172000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (110,11,'LOCAL_INCOME_TAX',17200);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (111,12,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (112,12,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (113,12,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (114,12,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (115,12,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (116,12,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (117,12,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (118,12,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (119,12,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (120,12,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (121,13,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (122,13,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (123,13,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (124,13,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (125,13,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (126,13,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (127,13,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (128,13,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (129,13,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (130,13,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (131,14,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (132,14,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (133,14,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (134,14,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (135,14,'NATIONAL_PENSION',166500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (136,14,'HEALTH_INSURANCE',131165);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (137,14,'LONG_TERM_CARE_INSURANCE',16985);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (138,14,'EMPLOYMENT_INSURANCE',33300);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (139,14,'INCOME_TAX',129500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (140,14,'LOCAL_INCOME_TAX',12950);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (141,15,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (142,15,'POSITION_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (143,15,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (144,15,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (145,15,'NATIONAL_PENSION',193500);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (146,15,'HEALTH_INSURANCE',152435);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (147,15,'LONG_TERM_CARE_INSURANCE',19740);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (148,15,'EMPLOYMENT_INSURANCE',38700);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (149,15,'INCOME_TAX',172000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (150,15,'LOCAL_INCOME_TAX',17200);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (151,16,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (152,16,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (153,16,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (154,16,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (155,16,'NATIONAL_PENSION',144000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (156,16,'HEALTH_INSURANCE',113440);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (157,16,'LONG_TERM_CARE_INSURANCE',14690);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (158,16,'EMPLOYMENT_INSURANCE',28799);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (159,16,'INCOME_TAX',112000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (160,16,'LOCAL_INCOME_TAX',11200);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (161,17,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (162,17,'POSITION_ALLOWANCE',400000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (163,17,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (164,17,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (165,17,'NATIONAL_PENSION',261000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (166,17,'HEALTH_INSURANCE',205610);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (167,17,'LONG_TERM_CARE_INSURANCE',26626);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (168,17,'EMPLOYMENT_INSURANCE',52199);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (169,17,'INCOME_TAX',261000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (170,17,'LOCAL_INCOME_TAX',26100);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (171,18,'MEAL_ALLOWANCE',200000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (172,18,'POSITION_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (173,18,'ANNUAL_LEAVE_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (174,18,'OVERTIME_ALLOWANCE',0);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (175,18,'NATIONAL_PENSION',144000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (176,18,'HEALTH_INSURANCE',113440);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (177,18,'LONG_TERM_CARE_INSURANCE',14690);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (178,18,'EMPLOYMENT_INSURANCE',28799);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (179,18,'INCOME_TAX',112000);
Insert into SBERP.SAL_PAY_ITEM (ITEM_ID,PAY_ID,ITEM_CODE,AMT) values (180,18,'LOCAL_INCOME_TAX',11200);

-- ------------------------------------------------------------
-- 11) sal_hist (급여 변경이력) : 12건
--     주의: 4개 신규 정책 테이블은 sal_hist.dom_type CHECK 제약(SALARY_STANDARD/
--     SALARY_PAYMENT/SALARY_ACCOUNT)에 포함되지 않으므로 이력 기록 대상이 아니다.
-- ------------------------------------------------------------
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (1,132,'허철아',134,1,'SALARY_STANDARD',1,'CREATE',NULL,'baseSal=2800000','사원 노경형 급여기준 최초 등록');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (2,132,'허철아',142,1,'SALARY_STANDARD',10,'CREATE',NULL,'baseSal=5800000','부장 안예준 급여기준 최초 등록');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (3,132,'허철아',133,1,'SALARY_STANDARD',12,'UPDATE','baseSal=3700000,actv=0(std_id=11)','baseSal=4300000,actv=1(std_id=12)','류상경 대리->과장 승진에 따른 급여기준 갱신(버저닝)');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (4,132,'허철아',136,1,'SALARY_STANDARD',14,'UPDATE','baseSal=4300000,actv=0(std_id=13)','baseSal=5000000,actv=1(std_id=14)','노철연 과장->차장 승진에 따른 급여기준 갱신(버저닝)');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (5,132,'허철아',137,1,'SALARY_PAYMENT',12,'STATUS_CHANGE','stat=PENDING','stat=REJECTED','급여 수령 계좌 정보 확인 필요로 반려');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (6,132,'허철아',140,1,'SALARY_PAYMENT',15,'STATUS_CHANGE','stat=PENDING','stat=APPROVED','승인 완료, 지급 대기');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (7,132,'허철아',143,1,'SALARY_PAYMENT',18,'CREATE',NULL,'stat=PENDING','7월 급여 지급 등록(자동 산정), 승인 대기');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (8,132,'허철아',132,1,'SALARY_PAYMENT',7,'STATUS_CHANGE','stat=APPROVED','stat=PAID','7월 급여 지급 완료');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (9,132,'허철아',132,1,'SALARY_ACCOUNT',1,'CREATE',NULL,'bankName=국민은행,acctNo=123456-78-901234','본인 급여 수령 계좌 최초 등록');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (10,133,'류상경',133,1,'SALARY_ACCOUNT',2,'CREATE',NULL,'bankName=신한은행,acctNo=110-456-789012','본인 급여 수령 계좌 최초 등록');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (11,132,'허철아',142,1,'SALARY_ACCOUNT',11,'CREATE',NULL,'bankName=하나은행,acctNo=567-890123-45678','관리자 대행 등록(신규 입사자)');
Insert into SBERP.SAL_HIST (HIST_ID,ACTOR_EMP_ID,ACTOR_NAME,TRGT_EMP_ID,COM_ID,DOM_TYPE,TRGT_ID,CHG_TYPE,BFR_VAL,AFT_VAL,DESCR) values (12,139,'한도훈',139,1,'SALARY_ACCOUNT',8,'UPDATE','bankName=우리은행,acctNo=110-000-111111','bankName=SC제일은행,acctNo=110-567-890123','주거래 은행 변경으로 계좌 정보 수정');

COMMIT;